server:
  port: 80
spring:
  application:
    name: cloud-order-service

eureka:
  instance:
    hostname: localhost
    instance-id: order80
    prefer-ip-address: true   #显示出ip
    #客户端向服务注册中心发送心跳间隔(默认30秒)
    lease-renewal-interval-in-seconds: 30
    #最后一次心跳后，剔除服务等待时间(默认90秒)
    lease-expiration-duration-in-seconds: 90

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://server1:7001/eureka/,http://server2:7002/eureka/



