server:
  port: 9002
spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      routes:
          - id: route1   #路由Id，没有固定要求但要求唯一
            #uri: http://localhost:8081 #匹配提供服务的路由地址
            uri: lb://cloud-payment-service
            predicates:
                   Path=/payment/get/** #断言，路径相匹配后提供路由
          - id: route2   #路由Id，没有固定要求但要求唯一
            uri: http://localhost:8081 #匹配提供服务的路由地址
            predicates:
                   Path=/payment/do/** #断言，路径相匹配后提供路由
      discovery:
        locator:
          enabled: true  #开启从注册中心创建动态路由的功能，利用微服务名进行路由

eureka:
  instance:
    hostname: localhost
    instance-id: gateway9002
    prefer-ip-address: true   #显示出ip
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/




