server:
  port: 7002

eureka:
  instance:
    hostname: server2 #eureka服务端的实例名
  client:
    #false代表不向服务注册中心注册自己
    register-with-eureka: false
    #false代表只需维护服务注册中心注册的服务实例而不用去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka交互的地址(查询和注册服务)
      defaultZone: http://server1:7001/eureka/
