server:
  port: 80
spring:
  application:
    name: cloud-order-feign-hystrix-service

eureka:
  instance:
    hostname: localhost
    instance-id: order80

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://server1:7001/eureka/

#修改Feign的默认超时时间(1s)全局配置
#ribbon:
#  #连接超时
#  ConnectTimeout: 5000
#  #连接成功后读取到可用资源超时
#  ReadTimeout: 5000

#开启客户端Hystrix
feign:
  hystrix:
    enabled: true
